### ISSUE TITLE
pip installation fails when offline

### ISSUE THREAD

**Issue by pepper-jk** [tklab-tud/ID2T#48]
**Issue by [jens.klein](https://git.tk.informatik.tu-darmstadt.de/jens.klein)**
_Saturday May 26, 2018 at 18:07 GMT_
_Originally opened as https://git.tk.informatik.tu-darmstadt.de/SPIN/ID2T-toolkit/issues/126_

----

The installation of pip dependencies fails while offline. This is due to pip requesting hashes for the packages in cache before installing, this requires an internet connection.

    $ ./build.sh 
    Updating SQLiteCpp
    Detected OS: Arch Linux
    Packages: Checking...
    Packages: Found.
    Additional Packages: Checking...
    Additional Packages: Found.
    Collecting coverage==4.5.1 (from -r resources/requirements.txt (line 1))
      Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb1a8ec160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/coverage/
      Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb1a8ec4a8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/coverage/
      Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb1a8ecba8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/coverage/
      Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb1a8ec0f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/coverage/
      Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb1a8ec128>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/coverage/
      Could not find a version that satisfies the requirement coverage==4.5.1 (from -r resources/requirements.txt (line 1)) (from versions: )
    No matching distribution found for coverage==4.5.1 (from -r resources/requirements.txt (line 1))
    -- The C compiler identification is GNU 8.1.0
    -- The CXX compiler identification is GNU 8.1.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    [...]

This results in the python-venv not being setup probably and ID2T to crash on start, because of the missing dependencies:

    $ ./id2t -i resources/201804041400.pcap -a SMBScan-T                   
    Traceback (most recent call last):
      File "/home/pepper-jk/code/ID2T-toolkit/code/CLI.py", line 5, in <module>
        from Core.Controller import Controller
      File "/home/pepper-jk/code/ID2T-toolkit/code/Core/Controller.py", line 8, in <module>
        import pyparsing as pp
    ModuleNotFoundError: No module named 'pyparsing'

**Comment by pepper-jk** [comment]
**Comment by [jens.klein](https://git.tk.informatik.tu-darmstadt.de/api/v1/repos/SPIN/ID2T-toolkit/jens.klein)**
_Wednesday May 30, 2018 at 01:26 GMT_

----

Fixed in pull request #133.

**Comment by pepper-jk** [comment]
**Comment by [jens.klein](https://git.tk.informatik.tu-darmstadt.de/api/v1/repos/SPIN/ID2T-toolkit/jens.klein)**
_Wednesday May 30, 2018 at 01:26 GMT_

----
