### ISSUE TITLE
Loading a pcap with labels crashes ID2T

### ISSUE THREAD

**Issue by UndeadKernel** [tklab-tud/ID2T#91]
The crash is due to `self.statistics` being null in `BaseAttack.py` line 386.

The erro backtrace is:
```
Label file found. Loading labels...
Traceback (most recent call last):
  File "/home/boy/id2t/code/CLI.py", line 228, in <module>
    main(sys.argv[1:])
  File "/home/boy/id2t/code/CLI.py", line 223, in main
    cli.parse_arguments(args)
  File "/home/boy/id2t/code/CLI.py", line 107, in parse_arguments
    self.process_arguments()
  File "/home/boy/id2t/code/CLI.py", line 118, in process_arguments
    self.process_pcap()
  File "/home/boy/id2t/code/CLI.py", line 171, in process_pcap
    self.args.debug)
  File "/home/boy/id2t/code/Core/Controller.py", line 41, in __init__
    self.label_manager = LabelManager.LabelManager(self.pcap_src_path)
  File "/home/boy/id2t/code/Core/LabelManager.py", line 46, in __init__
    self.load_labels()
  File "/home/boy/id2t/code/Core/LabelManager.py", line 247, in load_labels
    attack.add_param_value(param_name, param_value, param_userspecified)
  File "/home/boy/id2t/code/Attack/BaseAttack.py", line 386, in add_param_value
    elif param_name != atkParam.Parameter.INTERVAL_SELECT_STRATEGY and self.statistics.is_query(value):
AttributeError: 'NoneType' object has no attribute 'is_query'
```

**Comment by pepper-jk** [comment]
```
ERROR: Parameter ip.src or parameter value [] not valid. Skipping parameter.
ERROR: Parameter mac.src or parameter value ['3c:50:94:e5:96:b5', 'd0:75:31:87:e0:53', '14:67:9a:9c:34:3f'] not valid. Skipping parameter.
```

```
Traceback (most recent call last):
  File "/home/pepper-jk/code/ID2T/code/CLI.py", line 228, in <module>
    main(sys.argv[1:])
  File "/home/pepper-jk/code/ID2T/code/CLI.py", line 223, in main
    cli.parse_arguments(args)
  File "/home/pepper-jk/code/ID2T/code/CLI.py", line 107, in parse_arguments
    self.process_arguments()
  File "/home/pepper-jk/code/ID2T/code/CLI.py", line 118, in process_arguments
    self.process_pcap()
  File "/home/pepper-jk/code/ID2T/code/CLI.py", line 205, in process_pcap
    controller.process_attacks(self.args.attack, self.args.rngSeed, self.args.time, self.args.inject_empty)
  File "/home/pepper-jk/code/ID2T/code/Core/Controller.py", line 169, in process_attacks
    self.label_manager.write_label_file(self.pcap_dest_path)
  File "/home/pepper-jk/code/ID2T/code/Core/LabelManager.py", line 167, in write_label_file
    xml_tree.appendChild(get_subtree_parameters(label.parameters))
  File "/home/pepper-jk/code/ID2T/code/Core/LabelManager.py", line 125, in get_subtree_parameters
    for param_key, param_value in parameters.items():
AttributeError: 'str' object has no attribute 'items'
```

**Comment by pepper-jk** [comment]
A new issue appeared: #92
